# VizArray

The VizArray package provides a simple way of visualizing 2d NumPy arrays using the [ipythonblocks](http://ipythonblocks.org/) library. The goal of VizArray is to help teach array based programming.

## Importing

The simplest way of using `vizarray` is by installing the [antipackage](https://github.com/ellisonbg/antipackage) package, which allows you to import modules directly from GitHub:

In [3]:
import numpy as np
import antipackage
import github.ellisonbg.misc.vizarray as va

Downloading:  https://raw.githubusercontent.com/ellisonbg/misc/master/vizarray.py
Installing module:  github.ellisonbg.misc.vizarray


## Automatic usage

If you call `enable`, `vizarray` will automatically be used as the default display method for all NumPy arrays:

In [4]:
va.enable()

In [5]:
a = np.random.rand(10,10)

In [6]:
a

array([[ 0.88093899,  0.82792803,  0.5400842 ,  0.03630553,  0.6852934 ,
         0.35109247,  0.80746883,  0.61634118,  0.11156948,  0.07307092],
       [ 0.92738222,  0.09568812,  0.96393483,  0.65567036,  0.02940336,
         0.88866678,  0.42551725,  0.0098331 ,  0.5590931 ,  0.56517421],
       [ 0.19106591,  0.65164515,  0.19907346,  0.73454812,  0.85723936,
         0.77162995,  0.41583635,  0.47481412,  0.21417374,  0.198313  ],
       [ 0.29403495,  0.53113105,  0.58444743,  0.30864197,  0.79096644,
         0.55404796,  0.98671353,  0.25668608,  0.34429083,  0.86638008],
       [ 0.21573657,  0.16961118,  0.4599151 ,  0.97642192,  0.05408123,
         0.21662792,  0.93153603,  0.76234681,  0.2514707 ,  0.6726269 ],
       [ 0.62089875,  0.4729617 ,  0.15558654,  0.64745502,  0.96310202,
         0.11325479,  0.27850142,  0.87863136,  0.74089129,  0.95426914],
       [ 0.02417458,  0.28159382,  0.61539473,  0.91130621,  0.10891015,
         0.13796112,  0.23658929,  0.58459228,  0.55623217,  0.4754506 ],
       [ 0.38752103,  0.72063164,  0.99315912,  0.48501256,  0.85497605,
         0.45010418,  0.89194701,  0.47846161,  0.01633607,  0.87035543],
       [ 0.61108464,  0.12660471,  0.77205819,  0.939078  ,  0.60155115,
         0.75013627,  0.28153102,  0.99296654,  0.08042268,  0.44428225],
       [ 0.34309774,  0.26216673,  0.30110086,  0.37251197,  0.76475964,
         0.32705186,  0.63689368,  0.73153614,  0.00789913,  0.32766598]])

Slicing works as expected:

In [7]:
a[0:2,0:2]

array([[ 0.88093899,  0.82792803],
       [ 0.92738222,  0.09568812]])

In [8]:
a[0,:]

array([ 0.88093899,  0.82792803,  0.5400842 ,  0.03630553,  0.6852934 ,
        0.35109247,  0.80746883,  0.61634118,  0.11156948,  0.07307092])

In [9]:
a[:,0:2]

array([[ 0.88093899,  0.82792803],
       [ 0.92738222,  0.09568812],
       [ 0.19106591,  0.65164515],
       [ 0.29403495,  0.53113105],
       [ 0.21573657,  0.16961118],
       [ 0.62089875,  0.4729617 ],
       [ 0.02417458,  0.28159382],
       [ 0.38752103,  0.72063164],
       [ 0.61108464,  0.12660471],
       [ 0.34309774,  0.26216673]])

You can set the colormap that is used with the `set_cmap` function, which accepts Matplotlib colormap names:

In [11]:
va.set_cmap('Blues')

In [12]:
a

array([[ 0.88093899,  0.82792803,  0.5400842 ,  0.03630553,  0.6852934 ,
         0.35109247,  0.80746883,  0.61634118,  0.11156948,  0.07307092],
       [ 0.92738222,  0.09568812,  0.96393483,  0.65567036,  0.02940336,
         0.88866678,  0.42551725,  0.0098331 ,  0.5590931 ,  0.56517421],
       [ 0.19106591,  0.65164515,  0.19907346,  0.73454812,  0.85723936,
         0.77162995,  0.41583635,  0.47481412,  0.21417374,  0.198313  ],
       [ 0.29403495,  0.53113105,  0.58444743,  0.30864197,  0.79096644,
         0.55404796,  0.98671353,  0.25668608,  0.34429083,  0.86638008],
       [ 0.21573657,  0.16961118,  0.4599151 ,  0.97642192,  0.05408123,
         0.21662792,  0.93153603,  0.76234681,  0.2514707 ,  0.6726269 ],
       [ 0.62089875,  0.4729617 ,  0.15558654,  0.64745502,  0.96310202,
         0.11325479,  0.27850142,  0.87863136,  0.74089129,  0.95426914],
       [ 0.02417458,  0.28159382,  0.61539473,  0.91130621,  0.10891015,
         0.13796112,  0.23658929,  0.58459228,  0.55623217,  0.4754506 ],
       [ 0.38752103,  0.72063164,  0.99315912,  0.48501256,  0.85497605,
         0.45010418,  0.89194701,  0.47846161,  0.01633607,  0.87035543],
       [ 0.61108464,  0.12660471,  0.77205819,  0.939078  ,  0.60155115,
         0.75013627,  0.28153102,  0.99296654,  0.08042268,  0.44428225],
       [ 0.34309774,  0.26216673,  0.30110086,  0.37251197,  0.76475964,
         0.32705186,  0.63689368,  0.73153614,  0.00789913,  0.32766598]])

In [13]:
t = np.linspace(0,2.0*np.pi,100)

In [14]:
t

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37918976,
        4.44265628,  4.5061228 ,  4.56958931,  4.63305583,  4.69652235,
        4.75998887,  4.82345539,  4.88692191,  4.95038842,  5.01385494,
        5.07732146,  5.14078798,  5.2042545 ,  5.26772102,  5.33118753,
        5.39465405,  5.45812057,  5.52158709,  5.58505361,  5.64852012,
        5.71198664,  5.77545316,  5.83891968,  5.9023862 ,  5.96585272,
        6.02931923,  6.09278575,  6.15625227,  6.21971879,  6.28318531])

In [15]:
np.sin(t)

array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,   3.17279335e-02,  -3.17279335e-02,
        -9.50560433e-02,  -1.58001396e-01,  -2.20310533e-01,
        -2.81732557e-01,  -3.42020143e-01,  -4.00930535e-01,
        -4.58226522e-01,  -5.13677392e-01,  -5.67059864e-01,
        -6.18158986e-01,  -6.66769001e-01,  -7.12694171e-01,
        -7.55749574e-01,  -7.95761841e-01,  -8.32569855e-01,
        -8.66025404e-01,  -8.95993774e-01,  -9.22354294e-01,
        -9.45000819e-01,  -9.63842159e-01,  -9.78802446e-01,
        -9.89821442e-01,  -9.96854776e-01,  -9.99874128e-01,
        -9.98867339e-01,  -9.93838464e-01,  -9.84807753e-01,
        -9.71811568e-01,  -9.54902241e-01,  -9.34147860e-01,
        -9.09631995e-01,  -8.81453363e-01,  -8.49725430e-01,
        -8.14575952e-01,  -7.76146464e-01,  -7.34591709e-01,
        -6.90079011e-01,  -6.42787610e-01,  -5.92907929e-01,
        -5.40640817e-01,  -4.86196736e-01,  -4.29794912e-01,
        -3.71662456e-01,  -3.12033446e-01,  -2.51147987e-01,
        -1.89251244e-01,  -1.26592454e-01,  -6.34239197e-02,
        -2.44929360e-16])

You can set the block size in pixels (default is 30):

In [17]:
va.set_block_size(10)

In [18]:
a

array([[ 0.88093899,  0.82792803,  0.5400842 ,  0.03630553,  0.6852934 ,
         0.35109247,  0.80746883,  0.61634118,  0.11156948,  0.07307092],
       [ 0.92738222,  0.09568812,  0.96393483,  0.65567036,  0.02940336,
         0.88866678,  0.42551725,  0.0098331 ,  0.5590931 ,  0.56517421],
       [ 0.19106591,  0.65164515,  0.19907346,  0.73454812,  0.85723936,
         0.77162995,  0.41583635,  0.47481412,  0.21417374,  0.198313  ],
       [ 0.29403495,  0.53113105,  0.58444743,  0.30864197,  0.79096644,
         0.55404796,  0.98671353,  0.25668608,  0.34429083,  0.86638008],
       [ 0.21573657,  0.16961118,  0.4599151 ,  0.97642192,  0.05408123,
         0.21662792,  0.93153603,  0.76234681,  0.2514707 ,  0.6726269 ],
       [ 0.62089875,  0.4729617 ,  0.15558654,  0.64745502,  0.96310202,
         0.11325479,  0.27850142,  0.87863136,  0.74089129,  0.95426914],
       [ 0.02417458,  0.28159382,  0.61539473,  0.91130621,  0.10891015,
         0.13796112,  0.23658929,  0.58459228,  0.55623217,  0.4754506 ],
       [ 0.38752103,  0.72063164,  0.99315912,  0.48501256,  0.85497605,
         0.45010418,  0.89194701,  0.47846161,  0.01633607,  0.87035543],
       [ 0.61108464,  0.12660471,  0.77205819,  0.939078  ,  0.60155115,
         0.75013627,  0.28153102,  0.99296654,  0.08042268,  0.44428225],
       [ 0.34309774,  0.26216673,  0.30110086,  0.37251197,  0.76475964,
         0.32705186,  0.63689368,  0.73153614,  0.00789913,  0.32766598]])

The `disable` function will return NumPy arrays to their usual display format:

In [20]:
va.disable()

In [21]:
a

array([[ 0.88093899,  0.82792803,  0.5400842 ,  0.03630553,  0.6852934 ,
         0.35109247,  0.80746883,  0.61634118,  0.11156948,  0.07307092],
       [ 0.92738222,  0.09568812,  0.96393483,  0.65567036,  0.02940336,
         0.88866678,  0.42551725,  0.0098331 ,  0.5590931 ,  0.56517421],
       [ 0.19106591,  0.65164515,  0.19907346,  0.73454812,  0.85723936,
         0.77162995,  0.41583635,  0.47481412,  0.21417374,  0.198313  ],
       [ 0.29403495,  0.53113105,  0.58444743,  0.30864197,  0.79096644,
         0.55404796,  0.98671353,  0.25668608,  0.34429083,  0.86638008],
       [ 0.21573657,  0.16961118,  0.4599151 ,  0.97642192,  0.05408123,
         0.21662792,  0.93153603,  0.76234681,  0.2514707 ,  0.6726269 ],
       [ 0.62089875,  0.4729617 ,  0.15558654,  0.64745502,  0.96310202,
         0.11325479,  0.27850142,  0.87863136,  0.74089129,  0.95426914],
       [ 0.02417458,  0.28159382,  0.61539473,  0.91130621,  0.10891015,
         0.13796112,  0.23658929,  0.58459228