# VizArray

The VizArray package provides a simple way of visualizing 2d NumPy arrays using the [ipythonblocks](http://ipythonblocks.org/) library. The goal of VizArray is to help teach array based programming.

## Importing

In [1]:
%matplotlib inline
import numpy as np
import vizarray

## Manual usage

To visualize a NumPy array, just pass it to the `vizarray.vizarray` function:

In [2]:
a = np.random.rand(10,10)

In [3]:
vizarray.vizarray(a)

## Automatic usage

If you call `enable_notebook`, `vizarray` will automatically be used as the default display method for all NumPy arrays:

In [4]:
vizarray.enable_notebook()

In [5]:
a

array([[ 0.40757099,  0.1817572 ,  0.64854632,  0.5665256 ,  0.21797424,
         0.88198307,  0.59328478,  0.14814611,  0.66887321,  0.50148364],
       [ 0.26050509,  0.50097652,  0.52283948,  0.09928335,  0.1372609 ,
         0.23969422,  0.89080929,  0.84870735,  0.67918145,  0.8803606 ],
       [ 0.52377011,  0.78982269,  0.03789964,  0.91032241,  0.32918112,
         0.600385  ,  0.41836973,  0.18588686,  0.81316566,  0.36657394],
       [ 0.68637939,  0.36921532,  0.76837074,  0.20041975,  0.09615646,
         0.44048807,  0.21225954,  0.67801696,  0.29816408,  0.59711574],
       [ 0.14779768,  0.06047233,  0.52872618,  0.07807344,  0.22471503,
         0.62748135,  0.3923704 ,  0.86212821,  0.36525458,  0.62610908],
       [ 0.03541459,  0.43252417,  0.62418026,  0.37498822,  0.38618418,
         0.5909517 ,  0.63998954,  0.91340551,  0.28396807,  0.18277296],
       [ 0.55384486,  0.23391519,  0.90874104,  0.7739711 ,  0.40598224,
         0.52132742,  0.84132396,  0.18862276,  0.61303793,  0.48451052],
       [ 0.06922383,  0.52104436,  0.25186819,  0.31214033,  0.48581611,
         0.0841071 ,  0.02663194,  0.73357068,  0.11383662,  0.78410077],
       [ 0.75222785,  0.76106838,  0.63603274,  0.69088666,  0.07417917,
         0.07010039,  0.89988162,  0.3806107 ,  0.62126808,  0.86166343],
       [ 0.70951191,  0.65486779,  0.91869925,  0.57354937,  0.00949937,
         0.89237004,  0.48462266,  0.01408788,  0.2768876 ,  0.06766195]])

## Basic API

Slicing works as expected:

In [6]:
a[0:2,0:2]

array([[ 0.40757099,  0.1817572 ],
       [ 0.26050509,  0.50097652]])

In [7]:
a[0,:]

array([ 0.40757099,  0.1817572 ,  0.64854632,  0.5665256 ,  0.21797424,
        0.88198307,  0.59328478,  0.14814611,  0.66887321,  0.50148364])

In [8]:
a[:,0:2]

array([[ 0.40757099,  0.1817572 ],
       [ 0.26050509,  0.50097652],
       [ 0.52377011,  0.78982269],
       [ 0.68637939,  0.36921532],
       [ 0.14779768,  0.06047233],
       [ 0.03541459,  0.43252417],
       [ 0.55384486,  0.23391519],
       [ 0.06922383,  0.52104436],
       [ 0.75222785,  0.76106838],
       [ 0.70951191,  0.65486779]])

You can set the colormap that is used with the `set_cmap` function, which accepts Matplotlib colormap names:

In [9]:
vizarray.set_cmap('Blues')

In [10]:
a

array([[ 0.40757099,  0.1817572 ,  0.64854632,  0.5665256 ,  0.21797424,
         0.88198307,  0.59328478,  0.14814611,  0.66887321,  0.50148364],
       [ 0.26050509,  0.50097652,  0.52283948,  0.09928335,  0.1372609 ,
         0.23969422,  0.89080929,  0.84870735,  0.67918145,  0.8803606 ],
       [ 0.52377011,  0.78982269,  0.03789964,  0.91032241,  0.32918112,
         0.600385  ,  0.41836973,  0.18588686,  0.81316566,  0.36657394],
       [ 0.68637939,  0.36921532,  0.76837074,  0.20041975,  0.09615646,
         0.44048807,  0.21225954,  0.67801696,  0.29816408,  0.59711574],
       [ 0.14779768,  0.06047233,  0.52872618,  0.07807344,  0.22471503,
         0.62748135,  0.3923704 ,  0.86212821,  0.36525458,  0.62610908],
       [ 0.03541459,  0.43252417,  0.62418026,  0.37498822,  0.38618418,
         0.5909517 ,  0.63998954,  0.91340551,  0.28396807,  0.18277296],
       [ 0.55384486,  0.23391519,  0.90874104,  0.7739711 ,  0.40598224,
         0.52132742,  0.84132396,  0.18862276,  0.61303793,  0.48451052],
       [ 0.06922383,  0.52104436,  0.25186819,  0.31214033,  0.48581611,
         0.0841071 ,  0.02663194,  0.73357068,  0.11383662,  0.78410077],
       [ 0.75222785,  0.76106838,  0.63603274,  0.69088666,  0.07417917,
         0.07010039,  0.89988162,  0.3806107 ,  0.62126808,  0.86166343],
       [ 0.70951191,  0.65486779,  0.91869925,  0.57354937,  0.00949937,
         0.89237004,  0.48462266,  0.01408788,  0.2768876 ,  0.06766195]])

In [11]:
t = np.linspace(0,2.0*np.pi,100)

In [12]:
t

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37918976,
        4.44265628,  4.5061228 ,  4.56958931,  4.63305583,  4.69652235,
        4.75998887,  4.82345539,  4.88692191,  4.95038842,  5.01385494,
        5.07732146,  5.14078798,  5.2042545 ,  5.26772102,  5.33118753,
        5.39465405,  5.45812057,  5.52158709,  5.58505361,  5.64852012,
        5.71198664,  5.77545316,  5.83891968,  5.9023862 ,  5.96585272,
        6.02931923,  6.09278575,  6.15625227,  6.21971879,  6.28318531])

In [13]:
np.sin(t)

array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,   3.17279335e-02,  -3.17279335e-02,
        -9.50560433e-02,  -1.58001396e-01,  -2.20310533e-01,
        -2.81732557e-01,  -3.42020143e-01,  -4.00930535e-01,
        -4.58226522e-01,  -5.13677392e-01,  -5.67059864e-01,
        -6.18158986e-01,  -6.66769001e-01,  -7.12694171e-01,
        -7.55749574e-01,  -7.95761841e-01,  -8.32569855e-01,
        -8.66025404e-01,  -8.95993774e-01,  -9.22354294e-01,
        -9.45000819e-01,  -9.63842159e-01,  -9.78802446e-01,
        -9.89821442e-01,  -9.96854776e-01,  -9.99874128e-01,
        -9.98867339e-01,  -9.93838464e-01,  -9.84807753e-01,
        -9.71811568e-01,  -9.54902241e-01,  -9.34147860e-01,
        -9.09631995e-01,  -8.81453363e-01,  -8.49725430e-01,
        -8.14575952e-01,  -7.76146464e-01,  -7.34591709e-01,
        -6.90079011e-01,  -6.42787610e-01,  -5.92907929e-01,
        -5.40640817e-01,  -4.86196736e-01,  -4.29794912e-01,
        -3.71662456e-01,  -3.12033446e-01,  -2.51147987e-01,
        -1.89251244e-01,  -1.26592454e-01,  -6.34239197e-02,
        -2.44929360e-16])

You can set the block size in pixels (default is 30):

In [14]:
vizarray.set_block_size(10)

In [15]:
a

array([[ 0.40757099,  0.1817572 ,  0.64854632,  0.5665256 ,  0.21797424,
         0.88198307,  0.59328478,  0.14814611,  0.66887321,  0.50148364],
       [ 0.26050509,  0.50097652,  0.52283948,  0.09928335,  0.1372609 ,
         0.23969422,  0.89080929,  0.84870735,  0.67918145,  0.8803606 ],
       [ 0.52377011,  0.78982269,  0.03789964,  0.91032241,  0.32918112,
         0.600385  ,  0.41836973,  0.18588686,  0.81316566,  0.36657394],
       [ 0.68637939,  0.36921532,  0.76837074,  0.20041975,  0.09615646,
         0.44048807,  0.21225954,  0.67801696,  0.29816408,  0.59711574],
       [ 0.14779768,  0.06047233,  0.52872618,  0.07807344,  0.22471503,
         0.62748135,  0.3923704 ,  0.86212821,  0.36525458,  0.62610908],
       [ 0.03541459,  0.43252417,  0.62418026,  0.37498822,  0.38618418,
         0.5909517 ,  0.63998954,  0.91340551,  0.28396807,  0.18277296],
       [ 0.55384486,  0.23391519,  0.90874104,  0.7739711 ,  0.40598224,
         0.52132742,  0.84132396,  0.18862276,  0.61303793,  0.48451052],
       [ 0.06922383,  0.52104436,  0.25186819,  0.31214033,  0.48581611,
         0.0841071 ,  0.02663194,  0.73357068,  0.11383662,  0.78410077],
       [ 0.75222785,  0.76106838,  0.63603274,  0.69088666,  0.07417917,
         0.07010039,  0.89988162,  0.3806107 ,  0.62126808,  0.86166343],
       [ 0.70951191,  0.65486779,  0.91869925,  0.57354937,  0.00949937,
         0.89237004,  0.48462266,  0.01408788,  0.2768876 ,  0.06766195]])

The `disable` function will return NumPy arrays to their usual display format:

In [16]:
vizarray.disable_notebook()

In [17]:
a

array([[ 0.40757099,  0.1817572 ,  0.64854632,  0.5665256 ,  0.21797424,
         0.88198307,  0.59328478,  0.14814611,  0.66887321,  0.50148364],
       [ 0.26050509,  0.50097652,  0.52283948,  0.09928335,  0.1372609 ,
         0.23969422,  0.89080929,  0.84870735,  0.67918145,  0.8803606 ],
       [ 0.52377011,  0.78982269,  0.03789964,  0.91032241,  0.32918112,
         0.600385  ,  0.41836973,  0.18588686,  0.81316566,  0.36657394],
       [ 0.68637939,  0.36921532,  0.76837074,  0.20041975,  0.09615646,
         0.44048807,  0.21225954,  0.67801696,  0.29816408,  0.59711574],
       [ 0.14779768,  0.06047233,  0.52872618,  0.07807344,  0.22471503,
         0.62748135,  0.3923704 ,  0.86212821,  0.36525458,  0.62610908],
       [ 0.03541459,  0.43252417,  0.62418026,  0.37498822,  0.38618418,
         0.5909517 ,  0.63998954,  0.91340551,  0.28396807,  0.18277296],
       [ 0.55384486,  0.23391519,  0.90874104,  0.7739711 ,  0.40598224,
         0.52132742,  0.84132396,  0.18862276